// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  NODE_VERSION: '22.11.0';
  BUN_VERSION: '1.2.1';
  NG_BUILD_OPTIMIZE_CHUNKS: '1';
  API: Fetcher;
  ASSETS: Fetcher;
}
