#:schema node_modules/wrangler/config-schema.json
name = "fantamanajer-angular-dev"
compatibility_date = "2024-09-25"
main = "./dist/server/server.mjs"
assets = { directory = "./dist/browser", binding = "ASSETS", not_found_handling = "single-page-application" }
services = [{ binding = "API", service = "reverse-proxy-fantamanajer" }]
routes = [{ pattern = "c3.fantamanajer.it", custom_domain = true }]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
