#:schema node_modules/wrangler/config-schema.json
name = "fantamanajer-angular-dev"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat_v2"]
main = "./dist/server/server.mjs"
assets = { directory = "./dist/browser", binding = "ASSETS", not_found_handling = "single-page-application", html_handling = "auto-trailing-slash", experimental_serve_directly = true }
services = [{ binding = "API", service = "fantamanajer-reverse-proxy" }]
routes = [{ pattern = "c3.fantamanajer.it", custom_domain = true }]
upload_source_maps = true

[placement]
mode = "smart"

[vars]
NODE_VERSION = "22.11.0"
BUN_VERSION = "1.2.1"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
