#:schema node_modules/wrangler/config-schema.json
name = "fantamanajer-angular-dev"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat_v2"]
main = "./dist/server/server.mjs"
services = [{ binding = "API", service = "fantamanajer-reverse-proxy" }]
upload_source_maps = true
workers_dev = false

[assets]
directory = "./dist/browser"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[route]
pattern = "fantamanajer.it"
custom_domain = true

[placement]
mode = "smart"

[vars]
NODE_VERSION = "22.11.0"
BUN_VERSION = "1.2.1"
NG_BUILD_OPTIMIZE_CHUNKS = "1"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
