#:schema node_modules/wrangler/config-schema.json
name = "fantamanajer-angular"
compatibility_date = "2023-11-22"
pages_build_output_dir = "dist/cloudflare"
services = [{ binding = "API", service = "fantamanajer-reverse-proxy" }]
upload_source_maps = true
