#:schema node_modules/wrangler/config-schema.json
name = "fantamanajer-angular"
compatibility_date = "2023-11-22"
pages_build_output_dir = "dist/cloudflare"
services = [{ binding = "API", service = "fantamanajer-reverse-proxy" }]
upload_source_maps = true
compatibility_flags = ["nodejs_compat_v2"]

[vars]
NODE_VERSION = "22.11.0"
BUN_VERSION = "1.2.1"
NG_BUILD_OPTIMIZE_CHUNKS = 1
