name:  Bundle size monitor

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '18.x'

      # Install dependencies
      - run: npm ci --force

      # Build and output webpack stats to dist/fantamanajer-angular/stats.json
      - run: npm run build:stats

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2.1.10
        with:
          webpackStatsFile: ./dist/stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
