name: Bundle size monitor
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'
      - name: Verify build
        run: |
          npm install --force
          npm run build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
